#!/bin/bash
# Getting the jars and starting the server

FORGE_VERSION=`wget -O - http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json | grep "\"${MCVERSION}-${FORGEVERSION}\"" | cut -f6 -d" " | sed s/\"//g | sed s/,//g`

if [ ! -f forge-${MCVERSION}-${FORGE_VERSION}-${MCVERSION}-universal.jar ] && [ ! -f forge-${MCVERSION}-${FORGE_VERSION}-universal.jar ]
then
  curl "https://s3.amazonaws.com/Minecraft.Download/versions/${MCVERSION}/minecraft_server.${MCVERSION}.jar" -o /data/minecraft_server.${MCVERSION}.jar

  # I have no idea why forge 1.8 do not
  if [ "${MCVERSION}" != "1.8"  ] && [ "${MCVERSION}" != "1.7.2"  ]
  then
    curl "http://files.minecraftforge.net/maven/net/minecraftforge/forge/${MCVERSION}-$FORGE_VERSION-${MCVERSION}/forge-${MCVERSION}-$FORGE_VERSION-${MCVERSION}-installer.jar" -o /data/forge_installer.jar
  else
    curl "http://files.minecraftforge.net/maven/net/minecraftforge/forge/${MCVERSION}-$FORGE_VERSION/forge-${MCVERSION}-$FORGE_VERSION-installer.jar" -o /data/forge_installer.jar
  fi

  java -jar forge_installer.jar --installServer
fi

#The server need an eula.txt file with eula=true to start
if [ ! -f /data/eula.txt ]
then
	echo "eula=TRUE" > /data/eula.txt
fi

# Run the forge minecraft server
if [ "${MCVERSION}" != "1.8"  ] && [ "${MCVERSION}" != "1.7.2"  ]
then
  java -Xms1024M -Xmx1024M -jar forge-${MCVERSION}-${FORGE_VERSION}-${MCVERSION}-universal.jar
else
  java -Xms1024M -Xmx1024M -jar forge-${MCVERSION}-${FORGE_VERSION}-universal.jar
fi
