#!/bin/bash

# Update steam account info to update/install the server
sed -i "s/USERNAME/${STEAM_USERNAME}/g" /server/steamcmd/starbound_update.txt
sed -i "s/PASSWORD/${STEAM_PASSWORD}/g" /server/steamcmd/starbound_update.txt

# Update the server on start
/server/steamcmd/steamcmd.sh +runscript starbound_update.txt

# Modified version of this script: https://www.youtube.com/watch?v=LwDQaye2TZs

# Cleaning the mods folder
rm /server/steamcmd/starbound/mods/*.pak
rmdir --ignore-fail-on-non-empty ./starbound/steamapps/workshop/content/533830/*
 
# Creating a symlink for every .pak file in the workshop folder to the mods folder
for dir in /server/steamcmd/starbound/steamapps/workshop/content/533830/*/
do
 dir=${dir%*/}
 echo Sym-linking mod ${dir##*/} into the mods folder
 ln -r -s /server/steamcmd/starbound/steamapps/workshop/content/533830/${dir##*/}/*.pak /server/steamcmd/starbound/mods/${dir##*/}.pak
done

# Run the starbound server
cd /server/steamcmd/starbound/linux
./starbound_server
