#!/bin/bash

#mumble server start script

# Copy the base mumble database to the data directory
if [ ! -f /data/database/mumble-server.sqlite ]
then
    mkdir -p /data/database/
    cp /var/lib/mumble-server/mumble-server.sqlite /data/database/mumble-server.sqlite
    chown -R mumble-server:mumble-server /data/database/
fi

# Copy default config if not present
if [ ! -f /data/mumble-server.ini ]
then
    cp /etc/mumble-server.ini /data/mumble-server.ini
    chown -R mumble-server:mumble-server /data/
fi

# Set Mumble SuperUser password and echo it
if [ ! -f /data/superuser_password.txt ]
then
    SUPERUSER_PASSWORD=`pwgen -c -n -1 15`
    echo $SUPERUSER_PASSWORD > /data/superuser_password.txt
    murmurd -ini /etc/mumble-server.ini -supw $SUPERUSER_PASSWORD
fi


# Start Mumble server
/usr/bin/supervisord
